
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.6.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
Prisma.prismaVersion = {
  client: "7.6.0",
  engine: "75cbdc1eb7150937890ad5465d861175c6624711"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.OrganizationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  razaoSocial: 'razaoSocial',
  cnpj: 'cnpj',
  slug: 'slug',
  plan: 'plan',
  active: 'active',
  email: 'email',
  phone: 'phone',
  zipCode: 'zipCode',
  address: 'address',
  addressNumber: 'addressNumber',
  complement: 'complement',
  neighborhood: 'neighborhood',
  city: 'city',
  state: 'state',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrganizationSettingsScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  enableWMS: 'enableWMS',
  enableProduction: 'enableProduction',
  enableFinance: 'enableFinance',
  enableAutomation: 'enableAutomation',
  defaultMarkup: 'defaultMarkup',
  taxRate: 'taxRate',
  validadeOrcamento: 'validadeOrcamento',
  enableFinanceReports: 'enableFinanceReports',
  allowDuplicatePhones: 'allowDuplicatePhones',
  requireDocumentKeyForEntry: 'requireDocumentKeyForEntry',
  enableCategoryAppropriation: 'enableCategoryAppropriation',
  defaultReceivableCategoryId: 'defaultReceivableCategoryId',
  defaultRevenueCategoryId: 'defaultRevenueCategoryId',
  freightExpenseAccountId: 'freightExpenseAccountId',
  taxExpenseAccountId: 'taxExpenseAccountId',
  inventoryValuationMethod: 'inventoryValuationMethod',
  defaultBackupPassword: 'defaultBackupPassword',
  recoveryToken: 'recoveryToken'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  email: 'email',
  password: 'password',
  name: 'name',
  role: 'role',
  roleId: 'roleId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MaterialTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  spedCode: 'spedCode',
  organizationId: 'organizationId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SpedAccountMappingScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  materialTypeId: 'materialTypeId',
  spedType: 'spedType',
  accountId: 'accountId',
  mappingType: 'mappingType',
  createdAt: 'createdAt'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  action: 'action',
  tableName: 'tableName',
  recordId: 'recordId',
  oldValues: 'oldValues',
  newValues: 'newValues',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
};

exports.Prisma.ProfileScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  type: 'type',
  name: 'name',
  document: 'document',
  email: 'email',
  phone: 'phone',
  address: 'address',
  city: 'city',
  state: 'state',
  zipCode: 'zipCode',
  isCustomer: 'isCustomer',
  isSupplier: 'isSupplier',
  isEmployee: 'isEmployee',
  creditLimit: 'creditLimit',
  paymentTerms: 'paymentTerms',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  addressNumber: 'addressNumber',
  balance: 'balance',
  userId: 'userId'
};

exports.Prisma.MaterialScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  format: 'format',
  costPerUnit: 'costPerUnit',
  unit: 'unit',
  controlUnit: 'controlUnit',
  conversionFactor: 'conversionFactor',
  width: 'width',
  height: 'height',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  categoryId: 'categoryId',
  defaultConsumptionFactor: 'defaultConsumptionFactor',
  defaultConsumptionRule: 'defaultConsumptionRule',
  expenseAccountId: 'expenseAccountId',
  inventoryAccountId: 'inventoryAccountId',
  minStockQuantity: 'minStockQuantity',
  sellWithoutStock: 'sellWithoutStock',
  trackStock: 'trackStock',
  ncm: 'ncm',
  ean: 'ean',
  spedType: 'spedType',
  materialTypeId: 'materialTypeId',
  averageCost: 'averageCost',
  currentStock: 'currentStock'
};

exports.Prisma.InventoryItemScalarFieldEnum = {
  id: 'id',
  materialId: 'materialId',
  width: 'width',
  length: 'length',
  height: 'height',
  thickness: 'thickness',
  quantity: 'quantity',
  location: 'location',
  isOffcut: 'isOffcut',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  productType: 'productType',
  pricingMode: 'pricingMode',
  salePrice: 'salePrice',
  minPrice: 'minPrice',
  costPrice: 'costPrice',
  markup: 'markup',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pricingRuleId: 'pricingRuleId',
  stockMinQuantity: 'stockMinQuantity',
  stockQuantity: 'stockQuantity',
  stockUnit: 'stockUnit',
  trackStock: 'trackStock',
  formulaData: 'formulaData',
  localFormulaId: 'localFormulaId',
  customFormula: 'customFormula',
  sellWithoutStock: 'sellWithoutStock',
  targetMarkup: 'targetMarkup',
  targetMargin: 'targetMargin',
  categoryId: 'categoryId',
  revenueAccountId: 'revenueAccountId'
};

exports.Prisma.ProductConfigurationScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  description: 'description',
  helpText: 'helpText',
  type: 'type',
  required: 'required',
  defaultValue: 'defaultValue',
  affectsComponents: 'affectsComponents',
  affectsPricing: 'affectsPricing',
  minValue: 'minValue',
  maxValue: 'maxValue',
  step: 'step',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ConfigurationOptionScalarFieldEnum = {
  id: 'id',
  configurationId: 'configurationId',
  label: 'label',
  value: 'value',
  description: 'description',
  priceModifier: 'priceModifier',
  priceModifierType: 'priceModifierType',
  priceOverride: 'priceOverride',
  additionalComponents: 'additionalComponents',
  removedComponents: 'removedComponents',
  componentModifiers: 'componentModifiers',
  isAvailable: 'isAvailable',
  displayOrder: 'displayOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  materialId: 'materialId',
  slotQuantity: 'slotQuantity'
};

exports.Prisma.OptionIncompatibilityScalarFieldEnum = {
  id: 'id',
  optionAId: 'optionAId',
  optionBId: 'optionBId',
  reason: 'reason',
  createdAt: 'createdAt'
};

exports.Prisma.ConfigurationTemplateScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  category: 'category',
  configurations: 'configurations',
  metadata: 'metadata',
  usageCount: 'usageCount',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OrderItemConfigurationScalarFieldEnum = {
  id: 'id',
  orderItemId: 'orderItemId',
  configurationId: 'configurationId',
  selectedValue: 'selectedValue',
  selectedOptionId: 'selectedOptionId',
  createdAt: 'createdAt'
};

exports.Prisma.ProductionWasteScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  materialId: 'materialId',
  componentId: 'componentId',
  plannedQuantity: 'plannedQuantity',
  actualQuantity: 'actualQuantity',
  wasteQuantity: 'wasteQuantity',
  wasteReason: 'wasteReason',
  reportedBy: 'reportedBy',
  reportedAt: 'reportedAt'
};

exports.Prisma.ProductStandardSizeScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  width: 'width',
  height: 'height',
  isDefault: 'isDefault'
};

exports.Prisma.ProductComponentScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  materialId: 'materialId',
  consumptionMethod: 'consumptionMethod',
  wastePercentage: 'wastePercentage',
  calculatedWastePercentage: 'calculatedWastePercentage',
  manualWastePercentage: 'manualWastePercentage',
  wasteUnits: 'wasteUnits',
  manualWasteUnits: 'manualWasteUnits',
  lastWasteUpdate: 'lastWasteUpdate',
  wasteCalculationPeriod: 'wasteCalculationPeriod',
  isOptional: 'isOptional',
  priority: 'priority',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductOperationScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  name: 'name',
  costPerMinute: 'costPerMinute',
  setupTime: 'setupTime'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  customerId: 'customerId',
  orderNumber: 'orderNumber',
  status: 'status',
  subtotal: 'subtotal',
  discount: 'discount',
  tax: 'tax',
  total: 'total',
  deliveryDate: 'deliveryDate',
  createdAt: 'createdAt',
  validUntil: 'validUntil',
  updatedAt: 'updatedAt',
  notes: 'notes',
  approvedAt: 'approvedAt',
  cancellationPaymentAction: 'cancellationPaymentAction',
  cancellationReason: 'cancellationReason',
  cancellationRefundAmount: 'cancellationRefundAmount',
  cancelledAt: 'cancelledAt',
  cancelledById: 'cancelledById',
  deliveredAt: 'deliveredAt',
  finishedAt: 'finishedAt',
  inProductionAt: 'inProductionAt',
  processStatusId: 'processStatusId'
};

exports.Prisma.OrderStatusHistoryScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  fromStatus: 'fromStatus',
  toStatus: 'toStatus',
  fromProcessStatusId: 'fromProcessStatusId',
  toProcessStatusId: 'toProcessStatusId',
  notes: 'notes',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  itemType: 'itemType',
  width: 'width',
  height: 'height',
  quantity: 'quantity',
  totalArea: 'totalArea',
  attributes: 'attributes',
  area: 'area',
  paperSize: 'paperSize',
  paperType: 'paperType',
  printColors: 'printColors',
  finishing: 'finishing',
  customSizeName: 'customSizeName',
  isCustomSize: 'isCustomSize',
  machineTime: 'machineTime',
  setupTime: 'setupTime',
  complexity: 'complexity',
  costPrice: 'costPrice',
  calculatedPrice: 'calculatedPrice',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  notes: 'notes',
  processStatusId: 'processStatusId',
  status: 'status',
  pricingRuleId: 'pricingRuleId',
  unitCostAtSale: 'unitCostAtSale',
  unitPriceAtSale: 'unitPriceAtSale',
  profitAtSale: 'profitAtSale',
  compositionSnapshot: 'compositionSnapshot',
  confirmedAt: 'confirmedAt'
};

exports.Prisma.DeliveryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  orderId: 'orderId',
  deliveryDate: 'deliveryDate',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DeliveryItemScalarFieldEnum = {
  id: 'id',
  deliveryId: 'deliveryId',
  orderItemId: 'orderItemId',
  quantity: 'quantity'
};

exports.Prisma.BudgetScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  customerId: 'customerId',
  budgetNumber: 'budgetNumber',
  status: 'status',
  subtotal: 'subtotal',
  discount: 'discount',
  tax: 'tax',
  total: 'total',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  validUntil: 'validUntil',
  notes: 'notes'
};

exports.Prisma.BudgetItemScalarFieldEnum = {
  id: 'id',
  budgetId: 'budgetId',
  productId: 'productId',
  itemType: 'itemType',
  width: 'width',
  height: 'height',
  quantity: 'quantity',
  totalArea: 'totalArea',
  attributes: 'attributes',
  paperSize: 'paperSize',
  paperType: 'paperType',
  printColors: 'printColors',
  finishing: 'finishing',
  customSizeName: 'customSizeName',
  isCustomSize: 'isCustomSize',
  machineTime: 'machineTime',
  setupTime: 'setupTime',
  complexity: 'complexity',
  costPrice: 'costPrice',
  calculatedPrice: 'calculatedPrice',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  notes: 'notes',
  processStatusId: 'processStatusId',
  status: 'status',
  pricingRuleId: 'pricingRuleId'
};

exports.Prisma.InventoryMovementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  inventoryItemId: 'inventoryItemId',
  type: 'type',
  quantity: 'quantity',
  reason: 'reason',
  orderId: 'orderId',
  userId: 'userId',
  createdAt: 'createdAt'
};

exports.Prisma.InventoryAlertScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  materialId: 'materialId',
  type: 'type',
  threshold: 'threshold',
  currentLevel: 'currentLevel',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.ProductionQueueScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  orderId: 'orderId',
  priority: 'priority',
  status: 'status',
  scheduledStart: 'scheduledStart',
  actualStart: 'actualStart',
  estimatedEnd: 'estimatedEnd',
  actualEnd: 'actualEnd',
  assignedTo: 'assignedTo',
  machineId: 'machineId',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionOperationScalarFieldEnum = {
  id: 'id',
  productionQueueId: 'productionQueueId',
  name: 'name',
  description: 'description',
  sequence: 'sequence',
  estimatedMinutes: 'estimatedMinutes',
  actualMinutes: 'actualMinutes',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt'
};

exports.Prisma.MachineScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  model: 'model',
  serialNumber: 'serialNumber',
  status: 'status',
  maxWidth: 'maxWidth',
  maxHeight: 'maxHeight',
  speedPerMinute: 'speedPerMinute',
  lastMaintenance: 'lastMaintenance',
  nextMaintenance: 'nextMaintenance',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  balance: 'balance',
  bank: 'bank',
  agency: 'agency',
  accountNumber: 'accountNumber',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  accountId: 'accountId',
  type: 'type',
  amount: 'amount',
  description: 'description',
  categoryId: 'categoryId',
  orderId: 'orderId',
  dueDate: 'dueDate',
  paidAt: 'paidAt',
  status: 'status',
  createdAt: 'createdAt',
  auditNotes: 'auditNotes',
  paymentMethodId: 'paymentMethodId',
  payableId: 'payableId',
  profileId: 'profileId',
  receivableId: 'receivableId',
  userId: 'userId',
  competenceDate: 'competenceDate',
  accrualDate: 'accrualDate',
  paymentDate: 'paymentDate'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  color: 'color',
  parentId: 'parentId',
  active: 'active',
  defaultProductionSteps: 'defaultProductionSteps',
  chartOfAccountId: 'chartOfAccountId',
  inventoryAccountId: 'inventoryAccountId',
  expenseAccountId: 'expenseAccountId'
};

exports.Prisma.PaymentMethodScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  feePercentage: 'feePercentage',
  installmentRules: 'installmentRules',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  accountId: 'accountId',
  feeCategoryId: 'feeCategoryId'
};

exports.Prisma.PendingChangesScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  organizationId: 'organizationId',
  requestedBy: 'requestedBy',
  requestedAt: 'requestedAt',
  changes: 'changes',
  originalData: 'originalData',
  status: 'status',
  reviewedBy: 'reviewedBy',
  reviewedAt: 'reviewedAt',
  reviewComments: 'reviewComments',
  priority: 'priority',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NotificationsScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  data: 'data',
  read: 'read',
  createdAt: 'createdAt'
};

exports.Prisma.StandardSizeScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  width: 'width',
  height: 'height',
  type: 'type',
  isDefault: 'isDefault',
  description: 'description',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionMaterialScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  type: 'type',
  costPrice: 'costPrice',
  salesPrice: 'salesPrice',
  unit: 'unit',
  properties: 'properties',
  inStock: 'inStock',
  supplier: 'supplier',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FinishScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  allowedTypes: 'allowedTypes',
  priceType: 'priceType',
  priceValue: 'priceValue',
  processingTime: 'processingTime',
  requiresSetup: 'requiresSetup',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AutomationRuleScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  trigger: 'trigger',
  action: 'action',
  conditions: 'conditions',
  enabled: 'enabled',
  runCount: 'runCount',
  lastRun: 'lastRun',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProcessStatusScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  color: 'color',
  icon: 'icon',
  parentId: 'parentId',
  mappedBehavior: 'mappedBehavior',
  allowEdition: 'allowEdition',
  displayOrder: 'displayOrder',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  scope: 'scope',
  hideFromFlow: 'hideFromFlow'
};

exports.Prisma.PricingRuleScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  active: 'active',
  type: 'type',
  formula: 'formula',
  config: 'config',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isLatest: 'isLatest',
  parentId: 'parentId',
  version: 'version'
};

exports.Prisma.FichaTecnicaInsumoScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  insumoId: 'insumoId',
  productId: 'productId',
  configurationOptionId: 'configurationOptionId',
  configurationGroupId: 'configurationGroupId',
  quantidade: 'quantidade',
  custoCalculado: 'custoCalculado',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  linkedQuantityVariable: 'linkedQuantityVariable',
  linkedVariable: 'linkedVariable'
};

exports.Prisma.InsumoFornecedorScalarFieldEnum = {
  id: 'id',
  insumoId: 'insumoId',
  fornecedorId: 'fornecedorId',
  precoCusto: 'precoCusto',
  referencia: 'referencia',
  ativo: 'ativo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MaterialReceiptScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  invoiceNumber: 'invoiceNumber',
  totalAmount: 'totalAmount',
  issueDate: 'issueDate',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  payableId: 'payableId'
};

exports.Prisma.MaterialSupplierScalarFieldEnum = {
  id: 'id',
  materialId: 'materialId',
  supplierId: 'supplierId',
  supplierCode: 'supplierCode',
  costPrice: 'costPrice',
  notes: 'notes',
  paymentTerms: 'paymentTerms',
  preferredPaymentDay: 'preferredPaymentDay',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MaterialReceiptItemScalarFieldEnum = {
  id: 'id',
  receiptId: 'receiptId',
  materialId: 'materialId',
  quantity: 'quantity',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountPayableScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  supplierId: 'supplierId',
  amount: 'amount',
  dueDate: 'dueDate',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccountReceivableScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  customerId: 'customerId',
  orderId: 'orderId',
  amount: 'amount',
  dueDate: 'dueDate',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ChartOfAccountScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  code: 'code',
  description: 'description',
  nature: 'nature',
  type: 'type',
  parentId: 'parentId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  systemRole: 'systemRole'
};

exports.Prisma.ProductionOrderScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  orderItemId: 'orderItemId',
  status: 'status',
  priority: 'priority',
  pickingList: 'pickingList',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductionStepScalarFieldEnum = {
  id: 'id',
  productionOrderId: 'productionOrderId',
  name: 'name',
  order: 'order',
  status: 'status',
  startedAt: 'startedAt',
  finishedAt: 'finishedAt',
  operatorId: 'operatorId'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  materialId: 'materialId',
  type: 'type',
  quantity: 'quantity',
  unitCost: 'unitCost',
  totalCost: 'totalCost',
  machineId: 'machineId',
  machineCounter: 'machineCounter',
  notes: 'notes',
  supplierId: 'supplierId',
  documentKey: 'documentKey',
  createdAt: 'createdAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  organizationId: 'organizationId',
  name: 'name',
  description: 'description',
  isSystem: 'isSystem',
  active: 'active',
  createdAt: 'createdAt'
};

exports.Prisma.RolePermissionScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  permissionKey: 'permissionKey'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.UserRole = exports.$Enums.UserRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  OPERATOR: 'OPERATOR',
  USER: 'USER',
  CUSTOMER: 'CUSTOMER'
};

exports.SpedAccountType = exports.$Enums.SpedAccountType = {
  INVENTORY: 'INVENTORY',
  EXPENSE: 'EXPENSE'
};

exports.ProfileType = exports.$Enums.ProfileType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY'
};

exports.MaterialFormat = exports.$Enums.MaterialFormat = {
  ROLL: 'ROLL',
  SHEET: 'SHEET',
  UNIT: 'UNIT'
};

exports.ControlUnit = exports.$Enums.ControlUnit = {
  UN: 'UN',
  M: 'M',
  M2: 'M2',
  ML: 'ML'
};

exports.ConsumptionRule = exports.$Enums.ConsumptionRule = {
  FIXED_UNIT: 'FIXED_UNIT',
  PRODUCT_AREA: 'PRODUCT_AREA',
  PERIMETER: 'PERIMETER',
  SPACING: 'SPACING'
};

exports.ItemType = exports.$Enums.ItemType = {
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
  PRINT_SHEET: 'PRINT_SHEET',
  PRINT_ROLL: 'PRINT_ROLL',
  LASER_CUT: 'LASER_CUT',
  UNIT: 'UNIT',
  SQUARE_METER: 'SQUARE_METER',
  TIME_AREA: 'TIME_AREA'
};

exports.PricingMode = exports.$Enums.PricingMode = {
  SIMPLE_AREA: 'SIMPLE_AREA',
  SIMPLE_UNIT: 'SIMPLE_UNIT',
  DYNAMIC_ENGINEER: 'DYNAMIC_ENGINEER'
};

exports.ConfigurationType = exports.$Enums.ConfigurationType = {
  SELECT: 'SELECT',
  NUMBER: 'NUMBER',
  BOOLEAN: 'BOOLEAN',
  TEXT: 'TEXT'
};

exports.OrderStatus = exports.$Enums.OrderStatus = {
  DRAFT: 'DRAFT',
  APPROVED: 'APPROVED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  FINISHED: 'FINISHED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

exports.DeliveryStatus = exports.$Enums.DeliveryStatus = {
  PENDING: 'PENDING',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED'
};

exports.BudgetStatus = exports.$Enums.BudgetStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
};

exports.MovementType = exports.$Enums.MovementType = {
  IN: 'IN',
  OUT: 'OUT',
  TRANSFER: 'TRANSFER',
  ADJUSTMENT: 'ADJUSTMENT',
  WASTE: 'WASTE'
};

exports.AlertType = exports.$Enums.AlertType = {
  LOW_STOCK: 'LOW_STOCK',
  OVERSTOCK: 'OVERSTOCK',
  EXPIRING: 'EXPIRING'
};

exports.ProductionStatus = exports.$Enums.ProductionStatus = {
  WAITING: 'WAITING',
  IN_PROGRESS: 'IN_PROGRESS',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED'
};

exports.StepStatus = exports.$Enums.StepStatus = {
  PENDING: 'PENDING',
  DOING: 'DOING',
  DONE: 'DONE'
};

exports.MachineType = exports.$Enums.MachineType = {
  PRINTER: 'PRINTER',
  CUTTER: 'CUTTER',
  LAMINATOR: 'LAMINATOR',
  PLOTTER: 'PLOTTER',
  OTHER: 'OTHER'
};

exports.MachineStatus = exports.$Enums.MachineStatus = {
  AVAILABLE: 'AVAILABLE',
  IN_USE: 'IN_USE',
  MAINTENANCE: 'MAINTENANCE',
  BROKEN: 'BROKEN'
};

exports.AccountType = exports.$Enums.AccountType = {
  CHECKING: 'CHECKING',
  SAVINGS: 'SAVINGS',
  CASH: 'CASH',
  CREDIT_CARD: 'CREDIT_CARD',
  RECEIVABLE: 'RECEIVABLE'
};

exports.TransactionType = exports.$Enums.TransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT'
};

exports.TransactionStatus = exports.$Enums.TransactionStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

exports.CategoryType = exports.$Enums.CategoryType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE'
};

exports.PaymentMethodType = exports.$Enums.PaymentMethodType = {
  PIX: 'PIX',
  CARD: 'CARD',
  CASH: 'CASH',
  TRANSFER: 'TRANSFER',
  BOLETO: 'BOLETO',
  OTHER: 'OTHER'
};

exports.PendingChangeStatus = exports.$Enums.PendingChangeStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

exports.PendingChangePriority = exports.$Enums.PendingChangePriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  CHANGE_REQUEST: 'CHANGE_REQUEST',
  CHANGE_APPROVED: 'CHANGE_APPROVED',
  CHANGE_REJECTED: 'CHANGE_REJECTED'
};

exports.StatusScope = exports.$Enums.StatusScope = {
  ORDER: 'ORDER',
  ITEM: 'ITEM',
  BOTH: 'BOTH'
};

exports.ReceiptStatus = exports.$Enums.ReceiptStatus = {
  PENDING: 'PENDING',
  BILLED: 'BILLED'
};

exports.PayableStatus = exports.$Enums.PayableStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

exports.ReceivableStatus = exports.$Enums.ReceivableStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

exports.AccountNature = exports.$Enums.AccountNature = {
  ASSET: 'ASSET',
  LIABILITY: 'LIABILITY',
  EQUITY: 'EQUITY',
  REVENUE: 'REVENUE',
  REVENUE_DEDUCTION: 'REVENUE_DEDUCTION',
  COST: 'COST',
  EXPENSE: 'EXPENSE',
  RESULT_CALCULATION: 'RESULT_CALCULATION',
  CONTROL: 'CONTROL'
};

exports.ChartAccountType = exports.$Enums.ChartAccountType = {
  SYNTHETIC: 'SYNTHETIC',
  ANALYTIC: 'ANALYTIC'
};

exports.AccountSystemRole = exports.$Enums.AccountSystemRole = {
  GENERAL: 'GENERAL',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  INVENTORY: 'INVENTORY',
  REVENUE_SALE: 'REVENUE_SALE',
  COST_EXPENSE: 'COST_EXPENSE',
  RECEIVABLE: 'RECEIVABLE',
  PAYABLE: 'PAYABLE',
  TAX: 'TAX',
  FIXED_ASSET: 'FIXED_ASSET',
  EQUITY: 'EQUITY'
};

exports.Priority = exports.$Enums.Priority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.StockMovementType = exports.$Enums.StockMovementType = {
  ENTRY: 'ENTRY',
  INTERNAL_CONSUMPTION: 'INTERNAL_CONSUMPTION',
  ADJUSTMENT: 'ADJUSTMENT'
};

exports.Prisma.ModelName = {
  Organization: 'Organization',
  OrganizationSettings: 'OrganizationSettings',
  User: 'User',
  MaterialType: 'MaterialType',
  SpedAccountMapping: 'SpedAccountMapping',
  AuditLog: 'AuditLog',
  Profile: 'Profile',
  Material: 'Material',
  InventoryItem: 'InventoryItem',
  Product: 'Product',
  ProductConfiguration: 'ProductConfiguration',
  ConfigurationOption: 'ConfigurationOption',
  OptionIncompatibility: 'OptionIncompatibility',
  ConfigurationTemplate: 'ConfigurationTemplate',
  OrderItemConfiguration: 'OrderItemConfiguration',
  ProductionWaste: 'ProductionWaste',
  ProductStandardSize: 'ProductStandardSize',
  ProductComponent: 'ProductComponent',
  ProductOperation: 'ProductOperation',
  Order: 'Order',
  OrderStatusHistory: 'OrderStatusHistory',
  OrderItem: 'OrderItem',
  Delivery: 'Delivery',
  DeliveryItem: 'DeliveryItem',
  Budget: 'Budget',
  BudgetItem: 'BudgetItem',
  InventoryMovement: 'InventoryMovement',
  InventoryAlert: 'InventoryAlert',
  ProductionQueue: 'ProductionQueue',
  ProductionOperation: 'ProductionOperation',
  Machine: 'Machine',
  Account: 'Account',
  Transaction: 'Transaction',
  Category: 'Category',
  PaymentMethod: 'PaymentMethod',
  PendingChanges: 'PendingChanges',
  Notifications: 'Notifications',
  StandardSize: 'StandardSize',
  ProductionMaterial: 'ProductionMaterial',
  Finish: 'Finish',
  AutomationRule: 'AutomationRule',
  ProcessStatus: 'ProcessStatus',
  PricingRule: 'PricingRule',
  FichaTecnicaInsumo: 'FichaTecnicaInsumo',
  InsumoFornecedor: 'InsumoFornecedor',
  MaterialReceipt: 'MaterialReceipt',
  MaterialSupplier: 'MaterialSupplier',
  MaterialReceiptItem: 'MaterialReceiptItem',
  AccountPayable: 'AccountPayable',
  AccountReceivable: 'AccountReceivable',
  ChartOfAccount: 'ChartOfAccount',
  ProductionOrder: 'ProductionOrder',
  ProductionStep: 'ProductionStep',
  StockMovement: 'StockMovement',
  Role: 'Role',
  RolePermission: 'RolePermission'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
